/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Frame;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.converter.DateStringConverter;
import javafx.util.converter.DateTimeStringConverter;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.xml.parsers.ParserConfigurationException;
import model.Ciudad;
import model.Evento;
import model.Usuario;
import org.jespxml.JespXML;
import org.jespxml.excepciones.TagHijoNotFoundException;
import org.jespxml.modelo.Tag;
import org.xml.sax.SAXException;
import services.IngresarEvento;
import services.IniciarSesion;
import services.ListadoTrabajadores;
import services.ListarEventos;
import services.ListarTrabajadoresSuscritos;
import services.SuscribirEvento;
import services.TomarAsistencia;
import tableModel.TM_Eventos;
import tableModel.TM_Usuarios;

/**
 *
 * @author DiegoDX
 */
public class App extends javax.swing.JFrame {
    private String url = "200.120.230.3";
    private String server = "http://"+url+":80/proyectoTIC/ProyectoTIC_WS/controller";
    private final int DISPONIBLES = 1;
    private final int INICIADOS = 2;
    private Usuario usuario;
    DefaultListModel modeloLista = new DefaultListModel();
    /**
     * Creates new form Inicio
     */
    public App() {
        initComponents();
        setLocationRelativeTo(null);
        cargarTablaEventos(DISPONIBLES);
        cargarTablaEventos(INICIADOS);
        cargarCiudades();
        listAInscritos.setModel(modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JF_Empresa = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEECrear = new javax.swing.JButton();
        txtIngresarEvento_direccion = new javax.swing.JTextField();
        txtIngresarEvento_personal = new javax.swing.JTextField();
        cboIngresarEvento_ciudad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboAnoInicio = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cboMesInicio = new javax.swing.JComboBox<>();
        cboHoraInicio = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        cboMinutoInicio = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cboDiaInicio = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cboAnoFin = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        cboMesFin = new javax.swing.JComboBox<>();
        cboHoraFin = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cboMinutoFin = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        cboDiaFin = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        JF_Admin = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdministrador = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtASupervisor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAEstado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listAInscritos = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listAsistio = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        JF_Supervisor = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEventosIniciados = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnAsistencia = new javax.swing.JButton();
        btnFinDeEvento = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_Trabajadores_Suscritos = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbl_Trabajadores_Asistentes = new javax.swing.JTable();
        JF_Trabajador = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblEventosDisponibles = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtEventoDisponible_empresa = new javax.swing.JTextField();
        txtEventoDisponible_Ciudad = new javax.swing.JTextField();
        txtEventoDisponible_Direccion = new javax.swing.JTextField();
        txtEventoDisponible_Inicio = new javax.swing.JTextField();
        txtEventoDisponible_Termino = new javax.swing.JTextField();
        btnSuscribir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtLogin_email = new javax.swing.JTextField();
        btnIngreso = new javax.swing.JButton();
        txtLogin_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();

        JF_Empresa.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ingresar Evento"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Complete los Campos :");

        jLabel5.setText("Ciudad :");

        jLabel6.setText("Dirrecion :");

        jLabel7.setText("Nº Solicitado :");

        btnEECrear.setText("Crear");
        btnEECrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEECrearActionPerformed(evt);
            }
        });

        txtIngresarEvento_direccion.setText("Calle falsa #123");

        txtIngresarEvento_personal.setText("15");

        jLabel8.setText("Inicio :");

        jLabel4.setText("Año :");

        cboAnoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));

        jLabel19.setText("Mes :");

        cboMesInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cboHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabel22.setText(":");

        cboMinutoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel21.setText("Hora : ");

        cboDiaInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel20.setText("Dia :");

        jLabel9.setText("Fin :");

        jLabel23.setText("Año :");

        cboAnoFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));

        jLabel25.setText("Mes :");

        cboMesFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cboHoraFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabel27.setText(":");

        cboMinutoFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel26.setText("Hora : ");

        cboDiaFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel24.setText("Dia :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEECrear)
                .addGap(145, 145, 145))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtIngresarEvento_personal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 222, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIngresarEvento_direccion)
                                    .addComponent(cboIngresarEvento_ciudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(cboAnoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(cboMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(cboDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboMinutoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(cboAnoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(cboMesFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(cboDiaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboMinutoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboIngresarEvento_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIngresarEvento_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIngresarEvento_personal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboAnoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(cboMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cboDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(cboHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(cboMinutoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cboAnoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(cboMesFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cboDiaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(cboHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(cboMinutoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnEECrear)
                .addContainerGap())
        );

        javax.swing.GroupLayout JF_EmpresaLayout = new javax.swing.GroupLayout(JF_Empresa.getContentPane());
        JF_Empresa.getContentPane().setLayout(JF_EmpresaLayout);
        JF_EmpresaLayout.setHorizontalGroup(
            JF_EmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_EmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JF_EmpresaLayout.setVerticalGroup(
            JF_EmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_EmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JF_Admin.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Estado de los eventos"));

        tblAdministrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAdministrador);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Asistencia Del Evento"));

        jLabel10.setText("Supervisor :");

        jLabel11.setText("Estado :");

        txtAEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAEstadoActionPerformed(evt);
            }
        });

        listAInscritos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listAInscritos);

        jLabel12.setText("Inscritos");

        listAsistio.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listAsistio);

        jLabel13.setText("Asistio");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtASupervisor)
                    .addComponent(txtAEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(82, 82, 82)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtASupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout JF_AdminLayout = new javax.swing.GroupLayout(JF_Admin.getContentPane());
        JF_Admin.getContentPane().setLayout(JF_AdminLayout);
        JF_AdminLayout.setHorizontalGroup(
            JF_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JF_AdminLayout.setVerticalGroup(
            JF_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JF_Supervisor.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Eventos Iniciados"));

        tblEventosIniciados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEventosIniciados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventosIniciadosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblEventosIniciados);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Toma De Asistencia"));

        btnAsistencia.setText("Asistencia");
        btnAsistencia.setEnabled(false);
        btnAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaActionPerformed(evt);
            }
        });

        btnFinDeEvento.setText("Fin de Evento");
        btnFinDeEvento.setEnabled(false);

        tbl_Trabajadores_Suscritos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Trabajadores_Suscritos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_Trabajadores_SuscritosMouseReleased(evt);
            }
        });
        jScrollPane8.setViewportView(tbl_Trabajadores_Suscritos);

        tbl_Trabajadores_Asistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tbl_Trabajadores_Asistentes);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAsistencia)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(btnFinDeEvento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnFinDeEvento)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout JF_SupervisorLayout = new javax.swing.GroupLayout(JF_Supervisor.getContentPane());
        JF_Supervisor.getContentPane().setLayout(JF_SupervisorLayout);
        JF_SupervisorLayout.setHorizontalGroup(
            JF_SupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_SupervisorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JF_SupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JF_SupervisorLayout.setVerticalGroup(
            JF_SupervisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_SupervisorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JF_Trabajador.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Eventos Disponibles"));

        tblEventosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEventosDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventosDisponiblesMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblEventosDisponibles);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informacion del Evento"));

        jLabel14.setText("Empresa :");

        jLabel15.setText("Ciudad : ");

        jLabel16.setText("Dirrecion :");

        jLabel17.setText("Fecha Inicio:");

        jLabel18.setText("Fecha termino:");

        txtEventoDisponible_empresa.setEditable(false);

        txtEventoDisponible_Ciudad.setEditable(false);

        txtEventoDisponible_Direccion.setEditable(false);

        txtEventoDisponible_Inicio.setEditable(false);

        txtEventoDisponible_Termino.setEditable(false);

        btnSuscribir.setText("Suscribir");
        btnSuscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEventoDisponible_Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(txtEventoDisponible_Ciudad)
                            .addComponent(txtEventoDisponible_empresa)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnSuscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEventoDisponible_Inicio)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEventoDisponible_Termino, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtEventoDisponible_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEventoDisponible_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtEventoDisponible_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtEventoDisponible_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtEventoDisponible_Termino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSuscribir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JF_TrabajadorLayout = new javax.swing.GroupLayout(JF_Trabajador.getContentPane());
        JF_Trabajador.getContentPane().setLayout(JF_TrabajadorLayout);
        JF_TrabajadorLayout.setHorizontalGroup(
            JF_TrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JF_TrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JF_TrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JF_TrabajadorLayout.setVerticalGroup(
            JF_TrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_TrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtLogin_email.setText("email@supervisor.cl");
        txtLogin_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogin_emailActionPerformed(evt);
            }
        });

        btnIngreso.setText("Iniciar Sesión");
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });

        txtLogin_pass.setText("1234");
        txtLogin_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogin_passActionPerformed(evt);
            }
        });

        jLabel1.setText("Email de usuario :");

        jLabel2.setText("Clave:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngreso)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtLogin_email, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addComponent(txtLogin_pass)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLogin_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addComponent(txtLogin_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngreso)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/icono18.png"))); // NOI18N
        lblIcono.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lblIcono)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTablaEventos(int tipo){
        TM_Eventos modelEventos = new TM_Eventos(getEventos(tipo));
        
        switch(tipo){
            case DISPONIBLES:
                tblEventosDisponibles.setModel(modelEventos);
                break;                             
            case INICIADOS:
                tblEventosIniciados.setModel(modelEventos);
                break;                
        }
    }
    
    private ArrayList<Evento> getEventos(int tipo) {
        ArrayList<Evento> eventos = null;

        try {
            ListarEventos listar = new ListarEventos(server, tipo);
            JespXML a = new JespXML(new URL(listar.getUrl()));
            System.out.println(listar.getUrl());
            Tag t = a.leerXML();

            eventos = new ArrayList<>();
            int id_evento;
            String empresa, ciudad, direccion, inicio, termino;
            Tag tg_id, tg_empresa, tg_ciudad, tg_direccion, tg_inicio, tg_termino;

            Evento evento;
            for (Tag i : t.getTagsHijos()) {
                System.out.println("Hijo");

                tg_id = i.getTagHijoByName("id");
                tg_empresa = i.getTagHijoByName("empresa");
                tg_ciudad = i.getTagHijoByName("ciudad");
                tg_direccion = i.getTagHijoByName("direccion");
                tg_inicio = i.getTagHijoByName("inicio");
                tg_termino = i.getTagHijoByName("termino");

                empresa = tg_empresa.getContenido();
                ciudad = tg_ciudad.getContenido();
                direccion = tg_direccion.getContenido();
                inicio = tg_inicio.getContenido();
                termino = tg_termino.getContenido();
                id_evento = Integer.parseInt(tg_id.getContenido());

                evento = new Evento(id_evento, empresa, ciudad, inicio, termino, direccion);
                eventos.add(evento);

            }

        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TagHijoNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

        return eventos;
    }
    
    private void txtLogin_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogin_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogin_emailActionPerformed

    private void txtLogin_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogin_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogin_passActionPerformed

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        //iniciarSesion
        String mensaje,email,pass;
        
        email = txtLogin_email.getText();
        pass = txtLogin_pass.getText();
        
        try {
            usuario = getUsuario(email, pass); 
            mensaje = "Bienvenido "+usuario.getNombre()+" "+usuario.getApellido();
            
            JOptionPane.showMessageDialog(this, mensaje, "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
            txtLogin_email.setText("");
            txtLogin_pass.setText("");
            
            //ocultar ventana
            hide();
            
            //rescatar permiso
            switch (usuario.getId_permiso()) {
                case (1):
                    JF_Admin.pack();
                    JF_Admin.setLocationRelativeTo(null);
                    JF_Admin.setVisible(true);                   
                    break;
                case (2):
                    JF_Empresa.pack();
                    JF_Empresa.setLocationRelativeTo(null);
                    JF_Empresa.setVisible(true);                      
                    break;
                case (3):   
                    JF_Supervisor.pack();
                    JF_Supervisor.setLocationRelativeTo(null);
                    JF_Supervisor.setVisible(true);                     
                    break;
                case (4):                    
                    JF_Trabajador.pack();
                    JF_Trabajador.setLocationRelativeTo(null);
                    JF_Trabajador.setVisible(true);                                         
                    break;
            }
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            JOptionPane.showMessageDialog(this, "Error, complete los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SAXException ex) {
            System.out.println(ex);
            mensaje = "Email o contraseña incorrecto";
            JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        } catch (TagHijoNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (NullPointerException ex) {
            mensaje = "Email o contraseña incorrecto";
            JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_btnIngresoActionPerformed

    private Usuario getUsuario(String mail, String pass) throws Exception {
        //getUsuario
        Usuario usuario = null;
        
        IniciarSesion login = new IniciarSesion(server, mail, pass);
        String url = login.getUrl();

        System.out.println(url);

        JespXML a = new JespXML(new URL(url));
        Tag tagInfo = a.leerXML();

        Tag tagID = tagInfo.getTagHijoByName("id");
        Tag tagPermiso = tagInfo.getTagHijoByName("permiso");
        Tag tagNombre = tagInfo.getTagHijoByName("nombre");
        Tag tagApellido = tagInfo.getTagHijoByName("apellido");

        int id = Integer.parseInt(tagID.getContenido());
        int id_permiso = Integer.parseInt(tagPermiso.getContenido());
        String nombre = tagNombre.getContenido();
        String apellido = tagApellido.getContenido();

        usuario = new Usuario(id, id_permiso, nombre, apellido);
        return usuario;
    }
    
    private void txtAEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAEstadoActionPerformed

    private void btnSuscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuscribirActionPerformed
        try {
            int fila = tblEventosDisponibles.getSelectedRow();
            String sId = tblEventosDisponibles.getValueAt(fila, 0).toString();
            int id_evento = Integer.parseInt(sId);

            SuscribirEvento suscribir = new SuscribirEvento(server, usuario.getId(), id_evento);
            String url = suscribir.getUrl();
            System.out.println(url);

            JespXML a = new JespXML(new URL(url)); 
            Tag tagInfo = a.leerXML();
            
            Tag tg_mensaje = tagInfo.getTagHijoByName("mensaje");
            String mensaje = tg_mensaje.getContenido();

            JOptionPane.showMessageDialog(this, mensaje, "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
        }catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SAXException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (TagHijoNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuscribirActionPerformed

    private void tblEventosDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventosDisponiblesMouseClicked
        try{
           String id_evento, empresa, ciudad, direccion, inicio, termino;
            int fila = tblEventosDisponibles.getSelectedRow();
            
            id_evento = tblEventosDisponibles.getValueAt(fila, 0).toString();
            
            empresa = tblEventosDisponibles.getValueAt(fila, 1).toString();
            ciudad = tblEventosDisponibles.getValueAt(fila, 2).toString();
            direccion = tblEventosDisponibles.getValueAt(fila, 3).toString();
            inicio = tblEventosDisponibles.getValueAt(fila, 4).toString();
            termino = tblEventosDisponibles.getValueAt(fila, 5).toString();
            
            txtEventoDisponible_empresa.setText(empresa);
            txtEventoDisponible_Ciudad.setText(ciudad);
            txtEventoDisponible_Direccion.setText(direccion);
            txtEventoDisponible_Inicio.setText(inicio);
            txtEventoDisponible_Termino.setText(termino);
            
        }catch(Exception ex){
           JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblEventosDisponiblesMouseClicked

    private void tblEventosIniciadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventosIniciadosMouseClicked
        cargarTrabajadoresSuscritos();
        cargarTrabajadoresAsistentes();
    }//GEN-LAST:event_tblEventosIniciadosMouseClicked

    private void btnEECrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEECrearActionPerformed
        try {
            /*crearEvento*/
            String direccion = txtIngresarEvento_direccion.getText();
            String anoInicio;
            anoInicio = (String) cboAnoInicio.getSelectedItem();
            String mesInicio = (String) cboMesInicio.getSelectedItem();
            String diaInicio = (String) cboDiaInicio.getSelectedItem();
            String horaInicio = (String) cboHoraInicio.getSelectedItem();
            String minutoInicio = (String) cboMinutoInicio.getSelectedItem();
            
            String anofin = (String) cboAnoFin.getSelectedItem();
            String mesfin = (String) cboMesFin.getSelectedItem();
            String diafin = (String) cboDiaFin.getSelectedItem();
            String horafin = (String) cboHoraFin.getSelectedItem();
            String minutofin = (String) cboMinutoFin.getSelectedItem();
            
            String combinicionIn = anoInicio+"/"+mesInicio+"/"+diaInicio+" "+horaInicio+":"+minutoInicio+":00";
            String combinicionFin = anofin+"/"+mesfin+"/"+diafin+" "+horafin+":"+minutofin+":00";
            
            String inicio = combinicionIn;
            String termino = combinicionFin;
            int personal = Integer.parseInt(txtIngresarEvento_personal.getText());
            
            Ciudad ciudad = (Ciudad)cboIngresarEvento_ciudad.getSelectedItem();
            int idciudad = ciudad.getId();
            
            IngresarEvento ingresar = new IngresarEvento(server, idciudad, usuario.getId(), inicio, termino, direccion, personal);
            String url = ingresar.getUrl();
            System.out.println(url);
            
            JespXML a = new JespXML(new URL(url));
            Tag tagInfo = a.leerXML();
            
            Tag tg_mensaje = tagInfo.getTagHijoByName("mensaje");
            String mensaje = tg_mensaje.getContenido();
                    
            JOptionPane.showMessageDialog(this, mensaje, "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
        } catch (MalformedURLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (SAXException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (TagHijoNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEECrearActionPerformed

    private void btnAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaActionPerformed
        try {
            int evento = tblEventosIniciados.getSelectedRow();
            int trabajador = tbl_Trabajadores_Suscritos.getSelectedRow();
            int id_evento = Integer.parseInt(tblEventosIniciados.getValueAt(evento, 0).toString());
            int id_trabajador = Integer.parseInt(tbl_Trabajadores_Suscritos.getValueAt(trabajador, 0).toString());
            
            TomarAsistencia toma = new TomarAsistencia(server, id_trabajador, id_evento);
            String url = toma.getUrl();
            System.out.println(url);
            
            JespXML a = new JespXML(new URL(url));
            Tag tagInfo = a.leerXML();
            
            Tag tg_mensaje = tagInfo.getTagHijoByName("mensaje");
            String mensaje = tg_mensaje.getContenido();
                    
            JOptionPane.showMessageDialog(this, mensaje, "Confirmacion", JOptionPane.INFORMATION_MESSAGE);  
            cargarTrabajadoresAsistentes();
            cargarTrabajadoresSuscritos();            
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TagHijoNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAsistenciaActionPerformed

    private void tbl_Trabajadores_SuscritosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_Trabajadores_SuscritosMouseReleased
        try {
            // si hay algun trabajador
            int fila = tbl_Trabajadores_Suscritos.getSelectedRow();
            btnAsistencia.setEnabled(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbl_Trabajadores_SuscritosMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        String nombre=UIManager.getSystemLookAndFeelClassName();
        try {
            UIManager.setLookAndFeel(nombre);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame JF_Admin;
    private javax.swing.JFrame JF_Empresa;
    private javax.swing.JFrame JF_Supervisor;
    private javax.swing.JFrame JF_Trabajador;
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnEECrear;
    private javax.swing.JButton btnFinDeEvento;
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnSuscribir;
    private javax.swing.JComboBox<String> cboAnoFin;
    private javax.swing.JComboBox<String> cboAnoInicio;
    private javax.swing.JComboBox<String> cboDiaFin;
    private javax.swing.JComboBox<String> cboDiaInicio;
    private javax.swing.JComboBox<String> cboHoraFin;
    private javax.swing.JComboBox<String> cboHoraInicio;
    private javax.swing.JComboBox<Ciudad> cboIngresarEvento_ciudad;
    private javax.swing.JComboBox<String> cboMesFin;
    private javax.swing.JComboBox<String> cboMesInicio;
    private javax.swing.JComboBox<String> cboMinutoFin;
    private javax.swing.JComboBox<String> cboMinutoInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JList<String> listAInscritos;
    private javax.swing.JList<String> listAsistio;
    private javax.swing.JTable tblAdministrador;
    private javax.swing.JTable tblEventosDisponibles;
    private javax.swing.JTable tblEventosIniciados;
    private javax.swing.JTable tbl_Trabajadores_Asistentes;
    private javax.swing.JTable tbl_Trabajadores_Suscritos;
    private javax.swing.JTextField txtAEstado;
    private javax.swing.JTextField txtASupervisor;
    private javax.swing.JTextField txtEventoDisponible_Ciudad;
    private javax.swing.JTextField txtEventoDisponible_Direccion;
    private javax.swing.JTextField txtEventoDisponible_Inicio;
    private javax.swing.JTextField txtEventoDisponible_Termino;
    private javax.swing.JTextField txtEventoDisponible_empresa;
    private javax.swing.JTextField txtIngresarEvento_direccion;
    private javax.swing.JTextField txtIngresarEvento_personal;
    private javax.swing.JTextField txtLogin_email;
    private javax.swing.JPasswordField txtLogin_pass;
    // End of variables declaration//GEN-END:variables

    private void cargarCiudades() {
        cboIngresarEvento_ciudad.removeAllItems();
        cboIngresarEvento_ciudad.addItem(new Ciudad(1, 6, "Santiago"));
        cboIngresarEvento_ciudad.addItem(new Ciudad(2, 6, "Rancagua"));
    }

    private void cargarIconos() {
        
    }

    private void cargarTrabajadoresSuscritos() {
        try {
            int fila = tblEventosIniciados.getSelectedRow();
            int id_evento = Integer.parseInt(tblEventosIniciados.getValueAt(fila, 0).toString());
            
            //cargarUsuariosSuscritos
            ListarTrabajadoresSuscritos suscritos = new ListarTrabajadoresSuscritos(server, id_evento, 0);
            String url = suscritos.getUrl();
            System.out.println(url);
            
            JespXML a = new JespXML(new URL(url));
            Tag tagInfo = a.leerXML();
            Tag tg_id, tg_nombre, tg_apellido;
            ArrayList<Usuario> usuarios = new ArrayList<>(); 
            
            Usuario usuario;
            for(Tag tag: tagInfo.getTagsHijos()){
                tg_id = tag.getTagHijoByName("id");
                tg_nombre = tag.getTagHijoByName("nombre");
                tg_apellido = tag.getTagHijoByName("apellido");
                usuario = new Usuario(Integer.parseInt(tg_id.getContenido()), tg_nombre.getContenido(), tg_apellido.getContenido());
                usuarios.add(usuario);
            }
            
        TM_Usuarios modelUsuarios = new TM_Usuarios(usuarios);
        tbl_Trabajadores_Suscritos.setModel(modelUsuarios);
        
        } catch (MalformedURLException ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (ParserConfigurationException ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (SAXException ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (TagHijoNotFoundException ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
                System.out.println(ex.getMessage());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        }          
    }

    private void cargarTrabajadoresAsistentes() {
        try {
            int fila = tblEventosIniciados.getSelectedRow();
            int id_evento = Integer.parseInt(tblEventosIniciados.getValueAt(fila, 0).toString());
            
            //cargarUsuariosSuscritos
            ListarTrabajadoresSuscritos suscritos = new ListarTrabajadoresSuscritos(server, id_evento, 1);
            String url = suscritos.getUrl();
            System.out.println(url);
            
            JespXML a = new JespXML(new URL(url));
            Tag tagInfo = a.leerXML();
            Tag tg_id, tg_nombre, tg_apellido;
            ArrayList<Usuario> usuarios = new ArrayList<>(); 
            
            Usuario usuario;
            for(Tag tag: tagInfo.getTagsHijos()){
                tg_id = tag.getTagHijoByName("id");
                tg_nombre = tag.getTagHijoByName("nombre");
                tg_apellido = tag.getTagHijoByName("apellido");
                usuario = new Usuario(Integer.parseInt(tg_id.getContenido()), tg_nombre.getContenido(), tg_apellido.getContenido());
                usuarios.add(usuario);
            }
            
        TM_Usuarios modelUsuarios = new TM_Usuarios(usuarios);
        tbl_Trabajadores_Asistentes.setModel(modelUsuarios);
        
        } catch (MalformedURLException ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (ParserConfigurationException ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (SAXException ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        } catch (TagHijoNotFoundException ex) {
//            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
                System.out.println(ex.getMessage());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Confirmacion", JOptionPane.ERROR_MESSAGE);
        }                  
    }
}
